### ISSUE TITLE
Make GroupPats dropdown to remember user input between sessions

### ISSUE THREAD

**Issue by ilabutin** [Microsoft/perfview#446] opened 2017-11-20 08:37 UTC
Right now GroupPats dropdown remembers all user input, but does not keep it between sessions. It does remember last used value only.

I realize that when switching between different scenarios/apps this might not be valuable, but I primarily use PerfView for our applications where I would like to have my own groupings remembered.

So, suggestion is to let GroupPats to remember user input between sessions (but of course keep current logic about automatically adjusting "Just My App" option).

If this suggestion is OK, then I can do implementation.

**Comment by sharwell** [comment] 2017-11-20 11:49
My main concern here is how to handle a case where a user wants to get back to default values. It almost makes me wish I could have multiple saved presets, where each preset sets the grouping/folding/exclusions values.

**Comment by vancem** [comment] 2017-11-20 16:48
As @sharwell indicates, persistence of values can be negative (many of the entries are not worth saving and probably add to clutter), but that can undoubtedly be fixed (but please first suggest exactly what the experience is so we can agree we understand its positives and negatives)

Also note that there is already a feature in PerfView that should help you in the mean time.  

If you right click in the you will find 'Filter Params' -> 'Copy Filter Params' which basically copies all the filter parameters to the clipboard as XML.  You can also an operation to basically copy them back.   This allows you to remember 'special purpose' sets of parameters.   I realize this is not quite the experience you want, but may relieve some of the pressure.

**Comment by ilabutin** [comment] 2017-11-23 09:17
Idea of presets also came to my mind, but I thought it's too much. But let me describe how I see presets may be implemented.

_View preset_ is a combination of grouping/folding/exclusion fields. PerfView UI is modified to add extra dropdown of preset selection to the left of existing controls:
![perfview_2017-11-23_11-37-48](https://user-images.githubusercontent.com/1869103/33164578-822b8510-d044-11e7-99f5-4e0b6d96ccba.png)

Logic around this dropdown and old fields is following (I tried to put it into the sequence that users will experience, from basic usage to more advanced).

1. By default (if there we no saved presets) PerfView offers standard presets (those that are now in GroupPats dropdown).

1. Existing "Set as Default Grouping/Folding" menu item works as it is now - it just uses current view preset as default in all new views.

1. If one of predefined view presets is selected and user starts editing grouping/folding pattern manually, then preset selection dropdown is changed to "\*<Custom>" and save button becomes active. "\*" symbol in front of preset name means that current state of editboxes will not be preserved when window is closed.

1. If user wants to save his custom preset, he presses Save button and PerfView asks for new name. The preset is saved, but will not be default one for new views (unless File->Set as Default Grouping/Folding is used). The "\*" is removed from name.

1. If custom named user preset is shown and user starts editing grouping/folding/exclusion, then "\*" is added in front of name in the dropdown and Save button becomes enabled. There are no warnings about unsaved patterns upon window closing.

1. In order to manage all presets, the dropdown has last item called "...Manage" which opens a dialog where user can remove/edit presets. Default presets cannot be removed. Alternatively it can be implemented as main menu item, not as a special drop down item (this is even easier).

The preset editor will be just simple window with list of presets on the left and few edit boxes on the right (GroupPats/Fold/...).

Does this sound in line with your vision? @sharwell @vancem 

I'd be happy to implement support for that, if you agree.

**Comment by vancem** [comment] 2017-11-27 22:12
Thanks @ilabutin for working with us on the specification before jumping into implementation.    Because presets are an advanced feature, I would prefer them NOT to take up much screen real estate.    Also I don't really like having 'meta level' things like presets look the same 'non-meta-level' things (like  the grouping boxes.    Finally, it is better if there are no magic characters like * that have to be explained.  My inclination is to simply generalize the current ability to remember a preset.    I can be flexible but I was thinking
1. Add a new 'preset' top level menu item (between 'Regression' and 'help').  
2. This entry will have a 'New Preset' entry, as well as 'Managed Presets' and 'Preset Help' but it will also have menu items for every existing preset (thus varies over time, we do this for Diff and Regression already).  Note that you immediately get shortcuts for them based on their first character (Alt-P Alt-X will fetch the preset for the beginning with X).  
3. The New Preset will prompt for a name
4.  The Manage Preset will bring up a dialog that lets you list/delete presets
5. The default preset is just some special name (maybe the empty string).  

Note that my guess is that you will also want to be able to export and import them (easily, probably by default looking for a file called PerfViewPresets.xml, so you can easily set up a new machine with the presets you have accumulated).   

I would figure out what you think is the minimum viable feature and just to that.  we can expand it later.  

If you hate this, we can talk more, as I said, I can be flexible.  

Vance

**Comment by ilabutin** [comment] 2017-11-27 22:20
@vancem Thanks for the comment. The idea of having dedicated top-level menu for presets didn't come to my mind.
I think I'll implement what you've suggested and we'll see how it behaves.

Question: where do you think PerfView should keep presets saved by user? In the same settings file where all other information is kept between sessions?

**Comment by vancem** [comment] 2017-11-27 22:33
> Question: where do you think PerfView should keep presets saved by user? In the same settings file where all other information is kept between sessions?

I would save the info in the User.Config.  However I consider this file 'hidden', and opaque to users.   Thus I would also create an 'export' function that writes it to a file, as well as an 'import' operation  I would even always always try to read a file called PerfViewPresets.xml in the current directory at startup (and that could be the default  file to export to)..   That way it gets easy for users to move their presets to a new computer.   

There are details to this, but I think it is OK to start with just putting it in User.Config (where everything else goes), and worry about import and export as a separate feature.

**Comment by ilabutin** [comment] 2017-12-10 21:08
@vancem Now I have some time to do real implementation and I have final question.
Preset is just a remembered combination of current values of GroupPat, Folding, FoldPats, IncPats and ExcPats.
Few questions:
1. Should we include all 5 values as a preset?
1. How should dropdowns behave?
    1. I mean, should they contain standard 'predefined' values (like 'Just My App') or these values should go to default presets? In the latter case dropdowns will be empty when view is opened.
    1. Also, what if I have something custom entered in e.g. GroupPats and then I go to Preset menu and choose some preset? My idea is that this action should be considered like if I entered these values manually in editboxes - i.e. they appear in the dropdown, but will be forgotten in dropdowns when view is closed.

**Comment by vancem** [comment] 2017-12-13 23:11
@ilabutin  
> Should we include all 5 values as a preset?
seems like a good default answer.  If useful we could have a special value that means 'leave alone'.  
> How should dropdowns behave?
I think you have the right idea that presents should behave as if I typed the presets.   Thus the dropdowns remember the last X unique entries and presets are are remembered just just my typing.  
> I am inclined to say that GroupPats and other dropdowns should be filled as they are now
Yes.   We may decide they are redundant later, but it does not hurt to keep them at least for now.
> So, my suggestion is that by default PerfView behaves like it does now, but if I want to save some combination, then I can do that via Preset menu. And only those saved combinations are shown in Preset menu.
Yes
> Should we distinguish Presets for memory windows and CPU windows and only show relevant ones?
Great question.  I can see the usefulness of context sensitivity (different presets based on the kind of data being shown).   We already do this with the defaults (you get different defaults depending on what you are viewing.  

My take is that you should start with what is useful to you (you are probably happy with global (non-contextual) presets).   But your design should naturally generalize to allow users to have context (e.g. the suffix of the file being opened) if you so desire.

Also as mentioned, I think it is useful to remember this in the UserConfig, but to ALSO store it in a user-visiable file (that is probably placed beside the ETL file).   This makes it easy to 'export' your presents and use them on another machine/scenario.   Again you don't need to do this right away, but the design should allow for it.

**Comment by ilabutin** [comment] 2018-05-02 22:10
Once #654 is merged, this one can be closed.

**Comment by vancem** [comment] 2018-05-02 23:49
Addressed by #590 and #654

**Closed by vancem** 2018-05-02 23:49 UTC
