### ISSUE TITLE
I got a lot of .etl.zip files that have zeroes in CPU Msec for every process. CPU Stack is empty, but Thread Time Stack show correct information

### ISSUE THREAD

**Issue by vladimir-cheverdyuk-altium** [microsoft/perfview#1726] opened 2022-10-07 22:56 UTC
I got a quite a few of PerfView files that have zeroes in CPU Msec column for every process. It looks like this:
![image](https://user-images.githubusercontent.com/45857320/194672519-babcdd2c-c747-41e5-9e0a-3759d63b4fee.png)

If I choose process in CPU Stacks and open, it will not work. Every tab contains only ROOT.
But if I choose the same process in Thread Time Stacks and open, it will correctly show everything.

For example if I choose first process svchost I will get this CPU Stacks:
![image](https://user-images.githubusercontent.com/45857320/194673051-10c49864-ce46-4876-9c3e-e22180cfbb83.png)

And if I open it in Thread Time Stacks I will see this:
![image](https://user-images.githubusercontent.com/45857320/194673092-3dc3cde9-df59-4be2-915d-5a7d395ca1b1.png)

Is it correct?

I can provide .etl.zip file(s) directly to developer because it may contain some private information. 

Vlad

**Comment by ToyDragon** [comment] 2022-10-08 02:05
It sounds like a lot of things can cause this, but I was able to fix it by disabling real time virus protection in windows.
Settings > Windows Security > Virus and Thread Protection / Manage > Real-time protection

**Comment by vladimir-cheverdyuk-altium** [comment] 2022-10-08 02:52
But it actually works fine in Thread Time Stack. It is hard for me to imagine that AV can damage stacks for CPU but leave them be for Thread Time Stack. I also have suspicion that there are only one stack for both of them and of them just has extra information.

**Comment by brianrob** [comment] 2022-10-11 19:55
The reason that you see the thread time stacks view working but the CPU stacks not is because thread time depends upon two sets of events - CPU sampling and contextswitch/readythread events.  The contextswitch/readythread events are emitted when you hit these paths in the kernel, whereas the CPU samples are emitted via profiling interrupts.  It's the profiling interrupts that tend to get broken by kernel drivers, etc.

Are these on retail builds of the OS, or are these Windows Insider builds?

**Comment by vladimir-cheverdyuk-altium** [comment] 2022-10-11 20:00
From TraceInfo file I can see this:
OS Build Number 19041.2006.amd64fre.vb_release.191206-1406

**Comment by brianrob** [comment] 2022-10-11 20:50
I think these are both release builds.  I think we've looked at these together before.  I suspect that the best course of action for these is to file a Windows Feedback ticket.  This should help to get some eyes with operating system expertise to help investigate.  You can do this via the key combination Windows-F.

**Comment by vladimir-cheverdyuk-altium** [comment] 2022-10-11 20:56
Ok, I will leave feedback. Could you please tell me what kind terms should I use for this? I don't know many technical details and I would like to get their attention.

And just in case these are different reports from different companies.

**Comment by brianrob** [comment] 2022-10-12 16:48
Sure.  I think the key here is that you want to point out that you have a number of traces that should be capturing CPU sampling ETW events, but those events aren't being captured.  When you submit the feedback ticket, ideally submit it from a machine where this happened, so that the diagnostic information that is captured is relevant.  If this is not possible, make sure to provide Windows version information.  That's probably as much as you need to do until/unless they ask for more.  Please also provide a link to the feedback here.

**Comment by brianrob** [comment] 2022-10-12 20:26
I just learned of a feature in Microsoft Defender that may cause the behavior you're seeing, as it takes the PMU from ETW.  You can read more about it at https://www.microsoft.com/security/blog/2021/04/26/defending-against-cryptojacking-with-microsoft-defender-for-endpoint-and-intel-tdt/ and https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/defending-against-ransomware-with-microsoft-defender-for/ba-p/3243941.

The feature can be disabled by running `powershell.exe Set-MpPreference -DisableTDTFeature $true`.

@rbanks54, also adding you here, as this might also be what you're seeing in #1723.

**Comment by rbanks54** [comment] 2022-10-12 21:15
That's an interesting feature! Sounds like the ML model might need some tweaking if it's the cause 🙂

Thankfully,l I could use the work around for the conference talk I gave yesterday. Phew!

I'll give it a try on the two machines with problems later today and let you know the results

**Comment by rbanks54** [comment] 2022-10-13 09:51
@brianrob Success!!

The setting stays after a reboot as well, though trying to re-enable it throws an error
> _Set-MpPreference: Operation failed with the following error: 0x80004005. Operation: Set-MpPreference. Target: DisableTDTFeature._

Thank you so much for chasing things up!

**Comment by vladimir-cheverdyuk-altium** [comment] 2022-10-13 14:54
Thank you @brianrob and @rbanks54. I will add this to list of instructions and hopefully it will fix that issue.

**Comment by brianrob** [comment] 2022-10-13 17:39
Glad to hear that we're potentially making some progress in this area.  Weird that you can't re-enable it though.  Definitely worth calling out to folks in any instructions.  I'm going to close this issue for now, but @vladimir-cheverdyuk-altium, let me know if we need to re-open it.

**Closed by brianrob** 2022-10-13 17:39 UTC

**Comment by vladimir-cheverdyuk-altium** [comment] 2022-11-10 15:58
@brianrob that workaround helped. Today I had a case when customer sent PerfView file with 0 CPU everywhere. I asked customer to run command above and re-run PerfView and it helped. New file has proper CPU time everywhere.

Thank you again.

**Comment by brianrob** [comment] 2022-11-10 16:02
Awesome @vladimir-cheverdyuk-altium!  That's great to hear.  Thanks for letting me know.

**Comment by evgn** [comment] 2023-01-03 22:03
Hi folks!

If you're still interested, I did some research of this problem and left a comment [here](https://github.com/microsoft/perfview/issues/1723#issuecomment-1361165530).
