### ISSUE TITLE
StackViewer - The sort order in the byname tab should remain after making an update

### ISSUE THREAD

**Issue by daklimek** [Microsoft/perfview#96] opened 2016-06-09 00:53 UTC
I'm working in a stack viewer where I need to sort by Inc descending. After I find frames that I have analyzed, I remove them and then concentrate on the rest. When I start looking for other frames, I need to click the Inc column to sort by Inc instead of the default (which is Exc). It would be nice if the sort column didn't change between updates.

**Comment by sharwell** [comment] 2017-05-08 02:05
I believe this was fixed in #179

**Closed** 2017-05-17 22:50 UTC

**Comment by sharwell** [comment] 2017-05-17 22:52
Duplicate of #173.
