### ISSUE TITLE
[x64] Tutorial.exe -- entry point not found

### ISSUE THREAD

**Issue by bendono** [microsoft/perfview#355] opened 2017-08-18 04:16 UTC
Reproduction steps:

1. Download the 05/31/207 beta release. Both PerfView.exe and PerfView64.exe.
2. Run PerfView64.exe.
3. Click Alt+R.
4. In Command field, enter Tutorial.exe.
5. Press Enter.

An error indicating that the entry point is not found is displayed.
![image](https://user-images.githubusercontent.com/846533/29444044-5cf9c348-8417-11e7-9e24-b0768fbe699d.png)

Environment: Windows 7 Enterprise SP1, 64-bit. Language: English.

**Comment by tysmithnet** [comment] 2017-11-14 05:15
I'm also experiencing this. Does the 64 bit version only work on >= 8.1 ?

**Comment by tysmithnet** [comment] 2017-11-14 17:56
Or maybe you need c++ redistributable 2015

**Comment by tysmithnet** [comment] 2017-11-14 22:20
@vancem Does the may 64 bit version of perfview (https://github.com/Microsoft/perfview/releases/tag/V1.9.55) require a specific windows version in order to run? We are hoping that it will result in less broken stacks on server 2008r2

**Comment by vancem** [comment] 2017-11-14 22:36
@tysmithnet  - just FYI, the 64 bit version of PerfView is just a VERY thin wrapper that runs the same IL code but in a 64 bit process.  Thus it will have no semantic difference with the normal version of PerfView (unless you need more than 4GB of memory, in which case PerfVIew64 will not crash and the 32 bit version will).  

The error above is indeed what you get when you take an EXE that was built for later version versions of windows on an earlier version.   

This is probably because one or more of PerfView's support DLLs was not built to support older OSes.  

It is not clear this issue is worth fixing (just use the 32 bit version on old OSes as mentioned above) because it may be hard for me to get these support DLLs.

**Comment by SudhindraChegu** [comment] 2017-11-28 07:46
I am also facing the same issue.

Was this issue resolved after installing C++ redistributable 2015?

**Comment by vancem** [comment] 2017-11-29 00:23
There are potentially two separate issues here.  Basically whether you have this problem on the PerfView.exe (32 bit) version or on the PerfView64 (64 bit) version.  

If it is on PerfView64, (which this issue clearly indicates), the failure is by design (getting old versions of some of the dlls for 64 bit is problematic, and there really is not reason not to use the 32 bit version on old OSes.  

There is the problem that the error message is very bad.  PR #454 will address that however.

So I want to close this issue.   If there is a problem with the 32 bit (PerfView.exe) version on old OSs I want to fix that, but that is what issue #449 addresses. 

@SudhindraChegu  - it is my belief that installing any C++ redistributable will not help (the issue is that the DLLs need NEW apis, not that we are missing old APIs).

**Comment by SudhindraChegu** [comment] 2017-12-01 03:11
I agree with vance regarding C++ redistributable. 
That has not helped in resolving the issue.

Issue might be with the version KernelTraceControl.dll. After using the dll in %APPDATA%\PerfView\VER.*\amd64\, this issue was fixed.

**Comment by brianrob** [comment] 2019-10-18 17:36
Closing per @vancem's comment above.

**Closed by brianrob** 2019-10-18 17:36 UTC
