### ISSUE TITLE
[TraceEvent] Microsoft.Diagnostics.Tracing.Etlx.TraceCallStacks+CallStackInfo[] - High memory usage

### ISSUE THREAD

**Issue by suprak** [microsoft/perfview#1199] opened 2020-06-08 19:58 UTC
We've noticed that ever since update to the latest version of TraceEvent (from a much older one), we have been seeing much higher memory of TraceEvent. Mostly related to symbol resolution.

For instance from a dump (I can share internally),

```
0:000> !do 000001637fc31020
Name:        Microsoft.Diagnostics.Tracing.Etlx.TraceCallStacks+CallStackInfo[]
MethodTable: 00007ffe66678120
EEClass:     00007ffe666780a0
Size:        177629656(0xa9669d8) bytes
Array:       Rank 1, Number of elements 22203704, Type VALUETYPE (Print Array) 

0:000> !do 00000163b25e1020
Name:        Microsoft.Diagnostics.Tracing.Etlx.TraceCallStacks+CallStackInfo[]
MethodTable: 00007ffe66678120
EEClass:     00007ffe666780a0
Size:        134254640(0x8009030) bytes
Array:       Rank 1, Number of elements 16781827, Type VALUETYPE (Print Array)
```

That's 22million and 16milion entries per array.

Any plans or ideas on how TraceEvent memory usage can be improved?
We rely on TraceEvent as part of a production profiling workflow (can provide my context internally if you would like).

**Comment by brianrob** [comment] 2020-06-12 00:06
@suprak, do can you tell me which versions you're referring to here?  I suspect this might be caused by #1136.

**Comment by suprak** [comment] 2020-06-12 04:50
Sorry, should have mentioned that in my original post,

`<PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="2.0.49" />`

**Comment by brianrob** [comment] 2020-06-12 18:08
No worries.  Is 2.0.49 the new version that you're running or is that the old version?

**Comment by suprak** [comment] 2020-06-12 20:27
We upgraded from `2.0.2` back in February.
So `2.0.49` is what we are using currently.

**Comment by brianrob** [comment] 2022-06-13 23:18
@suprak, is this still an issue or should we close this?

**Comment by suprak** [comment] 2022-06-14 00:09
I haven't seen any alerts with this recently, so go ahead and close.

**Closed** 2022-06-14 00:34 UTC

**Comment by therickfactr** [comment] 2026-08-09 21:05
For anyone finding this thread later: we're seeing the same unbounded `TraceCallStacks+CallStackInfo[]` growth, but on the **real-time/EventPipe path in a long-lived server process** rather than during offline analysis, with production evidence (~0.6 GB/day to OOM, convicted by an A/B gcdump).

Since this one was closed in 2022 on reporter attrition rather than a resolution, I've opened it as a new issue rather than reviving a dormant thread: microsoft/perfview#2451. Happy to have it folded back in here if maintainers prefer.
