### ISSUE TITLE
Perfview thinks something is unreachable if it is in LogicalCallContext

### ISSUE THREAD

**Issue by ReverseBlade** [Microsoft/perfview#133] opened 2016-10-26 10:40 UTC
I had a memory leak that is due to some objects I put into LogicalCallContext. Perfview shows those as unreachable but actually this is a real memory leaks the thread run by some loop. Is there a way for making perfview to take ExecutionContexts to account ?

**Comment by vancem** [comment] 2016-10-27 15:00
Please try the following:  click the 'save etl' and try capturing a heap dump.  Let me know if this fixes the problem.

The basic issue is that while the default mechanism for capturing heap dumps is available on the most .NET platforms, it is a known issue that it may not create a perfect heap dump.   When you click 'save etl' it uses a different mechanism to capture the heap which should be perfectly accurate (but is newer and not available everywhere (and will pause the program during the dump).

**Comment by ReverseBlade** [comment] 2016-11-04 08:33
Hello Vance, 
Thanks that worked. But this leads to another problem. How will I decide if I should use Save ETL ? What would be my criteria as a guidance to select it. I mean "Take a dump, hmm doesn't look right, lets get it again with ETL" approach doesn't sound "correct".

**Comment by vancem** [comment] 2016-11-04 16:48
It is reasonable to consider changing the default to use the ETW mechanism to take a heap dump since it is more accurate.   This is now without other reproductions however, so a certain amount of thought is necessary before proceeding, but the idea for doing this has come up before.   Fell free to log an issue about asking for that (and link to this issue).    I will close this issue for now.

**Closed by vancem** 2016-11-04 16:48 UTC
