### ISSUE TITLE
CPU profiling records no samples after wakeup

### ISSUE THREAD

**Issue by brunom** [microsoft/perfview#1384] opened 2021-03-10 17:22 UTC
Profile data collected after my machine sleeps and wake up contain no samples for CPU Stacks. All process are at 0 CPU MSec. This seems to be a system issue under PerfView, as UIforETW doesn't work either, but I thought I could ask here at least where to ask. My PC is a Kaby Lake notebook with Windows 10 20H2.

**Comment by brianrob** [comment] 2021-03-16 13:52
@brunom, to confirm my understanding, are you saying that you start collection, then put the computer to sleep, and then wake it up and stop collection?

**Comment by brunom** [comment] 2021-03-16 14:13
@brianrob No, collection didn't need to be running when sleeping. I've suffered this some more and I now believe that sleeping wasn't the cause, but just the passage of time. I have to frequently restart the PC to do more profiling.

**Comment by brianrob** [comment] 2021-03-16 14:16
Ah, this sounds like there might be a driver that affecting your ability to capture CPU samples.  I've seen this before a few times - is it possible that you have some non-ETW profiling tools installed on your machine that might be installing drivers?  I have heard that this sort of things has occurred with VTune specifically.

**Comment by brunom** [comment] 2021-03-16 15:13
Yes, I use VTune. I tried first uninstalling it and then updating it, but maybe the uninstall wasn't clean enough. Thanks.

**Comment by brianrob** [comment] 2021-03-16 18:28
I suspect that you might be right on this.  If you're OK, I'd like to close this issue - let me know if you have any more questions on this.

**Closed** 2021-03-16 19:56 UTC

**Comment by nkolev92** [comment] 2021-05-27 17:01
I am running into the same issue :(

Any tips for diagnosing what the root cause is @brianrob @brunom 

I don't have VTune, and I only really figured out that it works after a restart after seeing this particular issue.

**Comment by brianrob** [comment] 2021-05-27 20:17
To be honest @nkolev92, I've not spent a lot of time diagnosing these types of issues in general, as other folks have historically figured these out before I learned of them.  I did learn recently that there is an HP performance utility that seems to also cause this.  You don't happen to be running on an HP machine, do you?

**Comment by nkolev92** [comment] 2021-05-27 23:16
Nope, no HP hardware/software on this machine.

It used to work, so I tried figuring out what new software I had installed, but no luck.

**Comment by brunom** [comment] 2021-05-28 01:52
@nkolev92 Sorry, I'm still suffering from this. It also breaks `powercfg /energy` which logs `CPU Utilization:Analysis Error`
What's your HW?

**Comment by nkolev92** [comment] 2021-06-04 19:47
@brunom 

After some digging, we might be hitting: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1302489 or equivalent. So this issue seems to have become more and more common.

**Comment by brunom** [comment] 2021-06-04 19:51
@nkolev92 Seems only MSies can see that page. Summary?

**Comment by nkolev92** [comment] 2021-06-04 20:44
Oh my bad, I meant to link the public version: https://developercommunity.visualstudio.com/t/No-Data-in-CPU-Usage-Tool-Windows-Updat/1384519
