### ISSUE TITLE
Need a way to distinguish code frame from other frames

### ISSUE THREAD

**Issue by northtyphoon** [Microsoft/perfview#94] opened 2016-06-02 14:29 UTC
When applying grouping rule (eg, !=>OTHER) , it may accidently group some Activity frames if their names contain "!". One solution is to add "Code" prefix to the full name of code frame.

**Comment by vancem** [comment] 2017-05-06 21:58
This is old enough that I am going to close it.    It is not clear how sever the problem is in practice.  If we come up with a SIMPLE, INTUITIVE solution, I would be fore doing it, but it is not clear such a solution exist. 

Lacking such a solution, we have to decide how much time an effort to invest (how severe the problem is).  If we think it is worth this, reopen this and describe the severity of the problem in more detail.

**Closed by vancem** 2017-05-06 21:58 UTC
