### ISSUE TITLE
Force GC returns false

### ISSUE THREAD

**Issue by solomon-okolie** [microsoft/perfview#1546] opened 2021-12-26 13:02 UTC
When I do a Force GC on a .NetCore3.1 or .Net6 process, status returns success= False. Below is the log captured.

Started with command line: "C:\Tools\Perfview\PerfView64.exe" 
PerfView Version: 2.0.74  BuildDate: Mon, 08 Nov 2021 22:34:08 GMT
PerfView Start Time 26/12/2021 13:56:25
Warning: PdbScope not found at C:\Tools\Perfview\PerfViewExtensions\PdbScope.exe
Disabling the Image Size Menu Item.
Warning: ILSize not found at C:\Tools\Perfview\PerfViewExtensions\ILSize.dll
Disabling the IL Size Menu Item.
Started: View
Completed: View   (Elapsed Time: 0.087 sec)
Started: Forcing a GC to process 26580
Starting Heap dump on Process 26580 running architecture Amd64.
Exec: "C:\Users\****\AppData\Roaming\PerfView\VER.2021-12-26.13.55.53.447\Amd64\HeapDump.exe" /ForceGC 26580
Loading the ETWClrProfiler.
Turning on debug privilege.
Could not enumerate .NET runtimes on the system.
  0.1s: Enabling JScript Heap Provider
  0.1s: Enabling EtwClrProfiler
  0.1s: Enabling CLR GC events
  0.1s: Requesting a JScript GC
  0.1s: Requesting a DotNet GC
  0.1s: Requesting .NET Native GC
 10.1s: Waiting for reply
 20.1s: Waiting for reply
 30.2s: Waiting for reply
 40.2s: Waiting for reply
 50.3s: Waiting for reply
 60.1s: Timed out after 60 seconds, GCs done but dead loops between .NET and JS heap may still exist.
 60.1s: Requesting ETWClrProfiler unload.
 60.1s: Shutting down ETW session
[ 60.1s: Done forcing GCs success=False]

Completed: Forcing a GC to process 26580   (Elapsed Time: 60.549 sec)

When done on a .Net4.8 process it works with status returning success=True

**Comment by brianrob** [comment] 2022-01-03 20:50
It looks like the error here is `Could not enumerate .NET runtimes on the system.`.

@davmason, do you know if we should be able to enumerate runtimes with the code at https://github.com/microsoft/perfview/blob/main/src/HeapDump/GCHeapDumper.cs#L783 in order to attach the profiler to a .NET 6 process?  From a quick test, this doesn't appear to work for .NET 6.

**Comment by davmason** [comment] 2022-01-04 09:46
No, that approach is unsupported and removed from coreclr. Even if you could get a CLRMetaHost, we don't support ICLRProfiling anymore.

The new way to attach a profiler since .net core 3.1 is to attach using the [DiagnosticsClient](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/diagnostics-client-library#attach-an-icorprofiler-profiler). We don't currently have a way to query per process for whether it has a loaded runtime, but we do provide `GetPublishedProcesses` so it should be easy to implement that method by checking if the process you care about is in the list of available processes to attach to.

@josalem as an aside, it seems worthwhile to add a `IsProcessPublished(int pid)` method to DiagnosticsClient

**Comment by mwijnands** [comment] 2022-05-30 15:31
Does this basically mean that ForceGC is not working for .NET Core 3.1+ processes? Are there any plans to support this?

**Comment by brianrob** [comment] 2022-06-09 19:22
I wouldn't expect this mechanism to come to .NET Core, but it is possible to force a GC and capture a heap snapshot via ETW / dotnet-trace.  I would recommend using this mechanism instead.

**Comment by brianrob** [comment] 2022-06-13 18:28
Closing as by design.

**Closed by brianrob** 2022-06-13 18:28 UTC
