### ISSUE TITLE
System.Windows.Automation.ElementNotAvailableException

### ISSUE THREAD

**Issue by MaherJendoubi** [microsoft/perfview#505] opened 2018-01-07 10:38 UTC
![image](https://user-images.githubusercontent.com/1798510/34648707-34fa0482-f39f-11e7-8b23-9993ad45e586.png)

**Comment by Alois-xx** [comment] 2018-01-08 07:24
Is this something which is reproducible? Are you trying to automate PerfView view UI Automation? 
Which version are you using?

**Comment by MaherJendoubi** [comment] 2018-01-09 09:21
I am not sure that this is something reproducible because I am trying to run PerfView 2.0 in run mode for a specific desktop .NET application on Windows 10.

**Comment by vancem** [comment] 2018-01-11 00:36
Thanks for taking the time to log an issue.  

Unfortunately, the information above is not sufficient to usefully debug this issue.  Can you give us more information, in particular

1. What where you doing when it happened?
2. Is it reproducible?
3. Note the stack above is in the windowing code, suggesting that it is not something specific to PerfView.   Do you have accessibility features turned on or other unusual OS or machine configuration?  Are you on a 'normal' version of the OS?  
4. Is it reproducible?   Does it reproduce on other machines?  
5. If it is easy to determine, do you know if older versions of PerfView worked?
6. Is there more stack available? (hit continue and click on the 'log' button to see what information is there) 

That should get us started...

Thanks

**Comment by samneirinck** [comment] 2018-03-15 11:27
I've just hit this specific issue, here are some answers:

1. This exception popped up when stopping a Collect > Collection session. 
2. Unfortunately this has only happened once
3. No accessibility features, nothing out of the ordinary on the OS. Not an insider build of Windows.
4. Same as 2
5. Unfortunately since it's not possible to reproduce, I'm not sure if older versions had the same behavior.
6. Log from the 'log' button:

```
Collection Dialog open.
Started: Collecting data C:\temp\PerfViewData.etl
[Kernel Log: C:\temp\PerfViewData.kernel.etl]
Kernel keywords enabled: Default
[User mode Log: C:\temp\PerfViewData.etl]
Enabling Provider:PerfViewLogger Level:Verbose Keywords:0xffffffffffffffff Stacks:0 Values: Guid:a8a71ac1-040f-54a2-07ca-00a89b5ab761
Enabling Providers specified by the user.
Parsing ETW Provider Spec: *Microsoft-ServiceFabric
Enabling Provider:*Microsoft-ServiceFabric Level:Verbose Keywords:0xffffffffffffffff Stacks:0 Values: Guid:631cd1dc-b34d-5a33-aa93-c3e5f9a80c25
[Starting collection at 2018-03-15 11:38:28]
[Collecting   10 sec: Size= 13.3 MB.]
[Collecting   20 sec: Size= 21.6 MB.]
[Collecting   30 sec: Size= 30.7 MB.]
[Manually Stopped (Gui)]
Stopping tracing for sessions 'NT Kernel Logger' and 'PerfViewSession'.
[Sending rundown command to CLR providers...]
[Use /NoNGenRundown if you don't care about pre V4.0 runtimes]
Enabling Provider:PerfViewLogger Level:Verbose Keywords:0xffffffffffffffff Stacks:0 Values: Guid:a8a71ac1-040f-54a2-07ca-00a89b5ab761
Waiting up to 120 sec for rundown events.  Use /RundownTimeout to change.
If you know your process has exited, use /noRundown qualifer to skip this step.
Rundown File Length: 0.1MB delta: 0.1MB
Rundown File Length: 0.1MB delta: 0.0MB
Rundown file has stopped growing, assuming rundown complete.
CLR Rundown took 2.134 sec.
Heap events were active for this trace.
Insuring .NET Allocation profiler not installed.
[Merging data files to PerfViewData.etl.  Can take 10s of seconds... (can skip if data analyzed on same machine with PerfView)]
Starting Merging of C:\temp\PerfViewData.etl
NGenSymbolFiles == false, skipping NGEN pdb generation
Merging took 5.9 sec
Moving C:\temp\PerfViewData.etl.new to C:\temp\PerfViewData.etl
Deleting temp file
Merge took 5.905 sec.
Merge output file C:\temp\PerfViewData.etl
Stop Completed at 2018-03-15 11:39:09
Completed: Collecting data C:\temp\PerfViewData.etl   (Elapsed Time: 41.193 sec)
Started: Opening PerfViewData.etl
Creating ETLX file C:\Users\Sam\AppData\Local\Temp\PerfView\PerfViewData_4e0f90c7.etlx from C:\temp\PerfViewData.etl
Collecting a maximum of 20,000,000 events.
[Opening a log file of size 50 MB of duration 33.1 sec.]
WARNING: Time:     181.4067 PID: 13060: Stack refers to event with time 28.1483 MSec that could not be found
WARNING: Two events with the same Timestamp 3645.0434
[Sec    1 Read    131,072 events. At  12,024ms.  Wrote   16MB ( 42%).  EstDone  0 min  1 sec.]
[Sec    2 Read    262,144 events. At  32,956ms.  Wrote   25MB ( 76%).  EstDone  0 min  0 sec.]
There were 15955 address that did not resolve to a module or method in process Idle (0)
There were 35 address that did not resolve to a module or method in process csrss (640)
There were 199 address that did not resolve to a module or method in process services (816)
There were 70 address that did not resolve to a module or method in process  (-1)
There were 2551 address that did not resolve to a module or method in process PerfView (13060)
There were 5379 address that did not resolve to a module or method in process <REDACTED>(3368)
There were 61 address that did not resolve to a module or method in process lsass (824)
There were 71 address that did not resolve to a module or method in process svchost (8)
There were 128 address that did not resolve to a module or method in process svchost (1040)
There were 25 address that did not resolve to a module or method in process svchost (1088)
There were 15 address that did not resolve to a module or method in process svchost (1352)
There were 95 address that did not resolve to a module or method in process svchost (1392)
There were 3900 address that did not resolve to a module or method in process Fabric (3264)
There were 10 address that did not resolve to a module or method in process svchost (1408)
There were 809 address that did not resolve to a module or method in process svchost (3068)
There were 26 address that did not resolve to a module or method in process svchost (2032)
There were 40 address that did not resolve to a module or method in process svchost (2204)
There were 3656 address that did not resolve to a module or method in process <REDACTED> (12844)
There were 18 address that did not resolve to a module or method in process svchost (2336)
There were 14 address that did not resolve to a module or method in process svchost (2364)
There were 185 address that did not resolve to a module or method in process svchost (2472)
There were 6 address that did not resolve to a module or method in process svchost (2676)
There were 62 address that did not resolve to a module or method in process svchost (2824)
There were 2214 address that did not resolve to a module or method in process dwm (3296)
There were 55 address that did not resolve to a module or method in process svchost (3012)
There were 117 address that did not resolve to a module or method in process svchost (3020)
There were 3571 address that did not resolve to a module or method in process slack (8944)
There were 18 address that did not resolve to a module or method in process svchost (3308)
There were 709 address that did not resolve to a module or method in process WUDFHost (3404)
There were 218 address that did not resolve to a module or method in process ExpressTray (2632)
There were 44 address that did not resolve to a module or method in process svchost (3472)
There were 243 address that did not resolve to a module or method in process GarminService (4524)
There were 31 address that did not resolve to a module or method in process dirmngr (4548)
There were 352 address that did not resolve to a module or method in process HealthService (4556)
There were 28 address that did not resolve to a module or method in process svchost (4568)
There were 48 address that did not resolve to a module or method in process svchost (4576)
There were 59 address that did not resolve to a module or method in process svchost (4592)
There were 281 address that did not resolve to a module or method in process svchost (4608)
There were 23 address that did not resolve to a module or method in process OfficeClickToRun (4620)
There were 7 address that did not resolve to a module or method in process NvTelemetryContainer (4700)
There were 51 address that did not resolve to a module or method in process svchost (4956)
There were 1391 address that did not resolve to a module or method in process OUTLOOK (12816)
There were 3401 address that did not resolve to a module or method in process MsMpEng (5040)
There were 5 address that did not resolve to a module or method in process svchost (5096)
There were 143 address that did not resolve to a module or method in process vmms (5676)
There were 14 address that did not resolve to a module or method in process svchost (6188)
There were 1076 address that did not resolve to a module or method in process slack (12252)
There were 59 address that did not resolve to a module or method in process DropboxUpdate (5064)
There were 122 address that did not resolve to a module or method in process NisSrv (8280)
There were 25 address that did not resolve to a module or method in process svchost (8788)
There were 10 address that did not resolve to a module or method in process svchost (9544)
There were 121 address that did not resolve to a module or method in process SearchIndexer (8968)
There were 13 address that did not resolve to a module or method in process svchost (11072)
There were 344 address that did not resolve to a module or method in process MonitoringHost (4928)
There were 5 address that did not resolve to a module or method in process csrss (10712)
There were 378 address that did not resolve to a module or method in process PerfWatson2 (7016)
There were 6 address that did not resolve to a module or method in process NVDisplay.Container (14216)
There were 53 address that did not resolve to a module or method in process MouseWithoutBorders (7068)
There were 326 address that did not resolve to a module or method in process MouseWithoutBorders (5476)
There were 13 address that did not resolve to a module or method in process svchost (9108)
There were 2574 address that did not resolve to a module or method in process explorer (12140)
There were 21 address that did not resolve to a module or method in process RuntimeBroker (13444)
There were 12 address that did not resolve to a module or method in process RuntimeBroker (1076)
There were 60 address that did not resolve to a module or method in process conhost (10972)
There were 89 address that did not resolve to a module or method in process ConEmuC64 (9176)
There were 314 address that did not resolve to a module or method in process ctfmon (1332)
There were 68 address that did not resolve to a module or method in process conhost (12704)
There were 130 address that did not resolve to a module or method in process TabTip (12500)
There were 8 address that did not resolve to a module or method in process MSASCuiL (12392)
There were 39 address that did not resolve to a module or method in process SurfaceDTX (5336)
There were 20 address that did not resolve to a module or method in process ONENOTEM (2500)
There were 17 address that did not resolve to a module or method in process Lightshot (6936)
There were 18 address that did not resolve to a module or method in process SettingSyncHost (5656)
There were 675 address that did not resolve to a module or method in process slack (12336)
There were 230 address that did not resolve to a module or method in process ConEmu64 (3048)
There were 92 address that did not resolve to a module or method in process ConEmuC64 (4884)
There were 65 address that did not resolve to a module or method in process powershell (5636)
There were 73 address that did not resolve to a module or method in process slack (12836)
There were 992 address that did not resolve to a module or method in process firefox (16004)
There were 24 address that did not resolve to a module or method in process iexplore (7748)
There were 22 address that did not resolve to a module or method in process iexplore (7824)
There were 3 address that did not resolve to a module or method in process SystemSettingsBroker (13112)
There were 131 address that did not resolve to a module or method in process mstsc (11240)
There were 7 address that did not resolve to a module or method in process RuntimeBroker (12560)
There were 742 address that did not resolve to a module or method in process devenv (12608)
There were 7 address that did not resolve to a module or method in process svchost (10952)
There were 96 address that did not resolve to a module or method in process slack (16036)
There were 208 address that did not resolve to a module or method in process lync (13608)
There were 29 address that did not resolve to a module or method in process UcMapi (7028)
There were 15 address that did not resolve to a module or method in process conhost (7904)
There were 37 address that did not resolve to a module or method in process ServiceHub.IdentityHost (9332)
There were 107 address that did not resolve to a module or method in process ServiceHub.VSDetouredHost (13856)
There were 48 address that did not resolve to a module or method in process ServiceHub.Host.CLR.x86 (13488)
There were 45 address that did not resolve to a module or method in process ServiceHub.SettingsHost (15200)
There were 82 address that did not resolve to a module or method in process ServiceHub.RoslynCodeAnalysisService32 (3556)
There were 78 address that did not resolve to a module or method in process Microsoft.Alm.Shared.Remoting.RemoteContainer (3168)
There were 24 address that did not resolve to a module or method in process vstest.discoveryengine.x86 (14600)
There were 75 address that did not resolve to a module or method in process powershell (17172)
There were 104 address that did not resolve to a module or method in process slack (5316)
There were 244 address that did not resolve to a module or method in process MouseWithoutBordersHelper (5688)
There were 102 address that did not resolve to a module or method in process FabricHost (4380)
There were 27 address that did not resolve to a module or method in process taskhostw (16992)
There were 70 address that did not resolve to a module or method in process FabricDCA (5380)
There were 47 address that did not resolve to a module or method in process conhost (9368)
There were 71 address that did not resolve to a module or method in process conhost (1600)
There were 44 address that did not resolve to a module or method in process FabricApplicationGateway (3412)
There were 1138 address that did not resolve to a module or method in process FabricGateway (4836)
There were 46 address that did not resolve to a module or method in process conhost (15968)
There were 37 address that did not resolve to a module or method in process conhost (16188)
There were 62 address that did not resolve to a module or method in process conhost (8492)
There were 34 address that did not resolve to a module or method in process conhost (12248)
There were 3525 address that did not resolve to a module or method in process <REDACTED>(3080)
There were 49 address that did not resolve to a module or method in process conhost (10728)
There were 927 address that did not resolve to a module or method in process <REDACTED> (17124)
There were 36 address that did not resolve to a module or method in process conhost (8912)
There were 52 address that did not resolve to a module or method in process FabricDnsService (16812)
There were 28 address that did not resolve to a module or method in process conhost (10620)
There were 57 address that did not resolve to a module or method in process smartscreen (12016)
There were 8408 address that did not resolve to a module or method in process firefox (14180)
There were 2795 address that did not resolve to a module or method in process firefox (10556)
There were 18616 address that did not resolve to a module or method in process firefox (9712)
There were 1431 address that did not resolve to a module or method in process firefox (8992)
There were 64 address that did not resolve to a module or method in process firefox (10536)
There were 731 address that did not resolve to a module or method in process cscript (9456)
There were 335 address that did not resolve to a module or method in process conhost (13592)
There were 2342 address that did not resolve to a module or method in process ImageBuilder (16028)
There were 151 address that did not resolve to a module or method in process conhost (7024)
There were 56 address that did not resolve to a module or method in process CtrlCSender (6656)
236 distinct processes.
Totals
   191,278 events.
    65,814 events with stack traces.
    61,226 events with code addresses in them.
  2,943,976 total code address instances. (stacks or other)
    97,790 unique code addresses. 
   743,783 unique stacks.
         0 unique managed methods parsed.
         0 CLR method event records.
[Conversion complete 191,278 events.  Conversion took 3 sec.]
A total of 97789 symbolic addresses were looked up.
Addresses outside any module: 3726 out of 97789 (3.8%)
Done with symbolic lookup.
ETL Size 50.135 MB ETLX Size 46.215 MB
Completed: Opening PerfViewData.etl   (Elapsed Time: 2.895 sec)
```

It's nothing critical, but since the dialog states it to be reported, here goes :) 

Hope it helps, and thanks for the great tool!

**Comment by brianrob** [comment] 2019-10-20 19:30
Closing as this does not seem to be reproducible.  Thank you for reporting this.

**Closed by brianrob** 2019-10-20 19:30 UTC
