### ISSUE TITLE
Add TraceEvent support for COMPACT_CSWITCH and other extended flag kernel providers

### ISSUE THREAD

**Issue by Zhentar** [Microsoft/perfview#791] opened 2018-11-11 03:48 UTC
CSWITCH is rather voluminous, so I would rather not enable it. COMPACT_CSWITCH, on the other hand, can be quite modest in volume. There are also some other potentially valuable extended flag kernel providers that I would be interested in using (memory info, power, minifilter IO). 

I've documented the secrets to invoking these providers on StartTrace here: https://gist.github.com/Zhentar/b12daf5683e6bcff455083f9f4bfa00e

**Comment by vancem** [comment] 2018-11-12 17:46
I have looked into supporting COMPACT_CSWITCH in the past.   The issue is for most uses (in particular the uses that PerfView needs, you need the STACK of the cswitch.     COMPACT_CSWITCH does not support this, and even if it did, it would not help much (since it is the stack, not the CSWITCH that takes up most of the space).  Thus I did not pursue it.

There are other potentially interesting kernel events, and we have added a few (e.g. RefSet), when their value was high.   I am open to doing more of these, but I want them to have a clear value.   You can start out simply use XPERF to collect the data and see what is really useful, and if there is something that pops, we can consider it.    Also keep in mind that using WPR/WPA is really a perfectly fine solution if they use case is specialized (users in these niches would probably find other aspects of WPA useful as well).    

I am closing this issue for now.   Feel free to open it (or other issues), if you feel my response above is inadequate.

**Closed by vancem** 2018-11-12 17:46 UTC

**Comment by Zhentar** [comment] 2018-11-12 22:55
To clarify, these are not things that I am intended to collect or analyze with PerfView; I am developing a standalone trace recorder using TraceEvent and would consume these programmatically or in WPA. Currently we mostly rely on WPR to collect field diagnostics but its use is severely hampered by the deluge of high frequency, low value events it collects.

COMPACT_CSWITCH I would like to support high precision attribution of CPU times to threads. It certainly does not deliver the value that COMPACT_SWITCH with stack traces does, but the low volume means we can just always turn it on without hampering our ability to collect extended duration traces.

Minifilter IO I want because it makes it real easy to pick out the impact of antivirus software, and the volume is quite manageable, so long as I filter it to the processes of interest.

**Comment by vancem** [comment] 2018-11-12 23:55
So if I understand you, you only care about actually parsing other kernel events.    These could be added 'outside' the TraceEvent library itself, by creating the necessary *TraceEventParser (normally you make this from a manifest, but kernel events have no manifest, so you have to reverse engineer them.   It is not too hard because you can compare against XPERF's parsed output.    The 'Dump' command in the 'events' view is your friend here.  

I an not really keen to put these specialty kernel parsers into the library because perfView does not have 'complete' support (it would not know how to generate them), and they are pretty specialized.
