### ISSUE TITLE
TraceEvent to implement ITraceEvent

### ISSUE THREAD

**Issue by suprak** [microsoft/perfview#163] opened 2017-02-28 19:08 UTC
Can we get TraceEvent to implement an interface?
It would make testing code that relies on the TraceEvent library (and TraceEvent class) so much easier.

Also, is the nuget for TraceEvent still being updated?

**Comment by vancem** [comment] 2017-05-06 21:30
> Can we get TraceEvent to implement an interface?
> It would make testing code that relies on the TraceEvent library (and TraceEvent class) so much easier

This will require some design discussion.   TraceEvent is not a single class but a group of related classes.   It was also designed to be as efficient as possible (it deals with GB sized data sets, perf is important, arguably it is too slow already).   

There has been a desire to expand TraceEvent to support other logging sources (e.g. from Linux), and that seems to be what you need as well to support testing.    Thus there are multiple reasons to think about this problem.   Most likely it will not be an actual ITraceEvent class but a way of easily hooking the data source to anything you want.   

The first step to this would be to describe your requirements (If TraceEvent could easily be hooked to a source you control would that work for you?)   

> Also, is the nuget for TraceEvent still being updated?

The intent is to keep the TraceEvent nuget package going using the source code here.   See Issue #178.

**Comment by sharwell** [comment] 2017-05-08 19:17
I can confirm that performance of method dispatch for this type is _critical_ to the performance of the application. I did several profiling runs over the past few days and it left no question. Note that I'm not saying it's necessarily going to be a problem to add this interface, but just that it will be important to be careful with the ramifications.

**Comment by suprak** [comment] 2017-05-08 19:44
@vancem 

Our scenario is that we rely on the TraceEvent library for processing events from ETLs. We have dedicated classes for dealing with specific event types (ex. `GCAllocationTickTraceData`, `SampledProfileTraceData`, etc).

However there is no easy way to create these events, short of taking a trace and using it for sample data purposes.

Adding an interface to TraceEvent is just a general suggestion, the bigger ask here is to allow better pathways for instantiating various events without relying on mocking out the full trace log etc.

**Comment by vancem** [comment] 2017-05-08 20:18
Generally what I have seen others do is to simply store the data for their tests.   It is easy, and works well, although it does not test corner cases.      I am not certain that an ITraceEvent would actually help as much as you would like because you really need the way of generating particular events (which technically TraceEvent (and thus ITraceEvent) never deals with (you would need to mock the Parsers that you care about.    

I think there are some things that might be done here, but I am not certain they are worth doing.   We can keep your scenario in mind as we expand TraceEvent for processing events that are not tied to ETL (e.g. Runtime events on Linux)

**Comment by brianrob** [comment] 2019-10-17 18:56
Closing this issue, as we have added support for more files, but all of that support is behind the existing surface.  If this is still an issue, I would recommend storing data files along with test cases as @vancem states above.

**Closed by brianrob** 2019-10-17 18:56 UTC
Labels: Suggestion
