### ISSUE TITLE
Unable to resolve the symbols for unmanaged code section when the CPU usage file is captured using dotnet trace command from power shell

### ISSUE THREAD

**Issue by mallikarjuna06** [microsoft/perfview#1255] opened 2020-08-31 23:41 UTC
Steps that I have followed.

Used PowerShell  and navigated till my project folder
--Set-Location C:\Users\....folder-structure...\MyProject.

From Powershell used below command to start the server of the application which exposes the endpoints
--start powershell{dotnet run}

Then I used below command to start to collect the CPU usage data 
--dotnet-trace collect -p 17156 --providers Microsoft-DotNETCore-SampleProfiler

where 17156 is the process id which is running the server.

Then I started to hit multiple get requests from PowerShell (another window) command itself to the server.

After I got the result for all the multiple requests I stopped collecting the dot-net trace data by pressing 
ctrl + c in the same window where I had started to collect the CPU usage data.

I opened the ***.nettrace file** that was generated when stopped the tracing data. Opened it using PerfView Tool.
Below is the attached screenshot of it both by name and call tree view in the tool

![PerfView](https://user-images.githubusercontent.com/21369057/91778389-29b4c500-eba7-11ea-88a5-e4066c3c4b5a.png)

![image](https://user-images.githubusercontent.com/21369057/91778420-3fc28580-eba7-11ea-9daf-4df356a789bb.png)

Majority of the CPU is used by unmanaged code. If I right-click and select the option "lookup for symbols" its not processing anything. It gives back the same data

**The main thing I wanted here was the CPU usage for "different Objects creation and dependency injecting them in controller, service, adapter etc classes" ie when hitting multiple requests at a concurrent time to server. Also How much CPU usage was made by different feature functions in my code. But I did not get any CPU usage data in the right format to analyze this. Everything is getting grouped as unmanaged code which is of no use and also cannot resolve the symbols for the un-managed code section.**

**Comment by mallikarjuna06** [comment] 2020-09-01 23:01
@brianrob @suprak

**Comment by adamsitnik** [comment] 2020-09-02 08:49
@mallikarjuna06 as far as I know this is by design. @noahfalk should be able to tell more

**Comment by noahfalk** [comment] 2020-09-02 11:38
> @mallikarjuna06 as far as I know this is by design

Thats correct, all of the dotnet-trace functionality is currently managed-code only. I hope to expand the capabilities of dotnet-trace in the future but for now if you want to profile unmanaged code you need to use OS specific tools that understand how to unwind and resolve that kind of code. On Windows ETW collection with PerfView, Visual Studio or WPA are common choices to do that.

A few other notes that might be useful:
1. In that callstack that ends WaitOneNoCheck() before the UNMANAGED_CODE node, the implementation of a WaitHandle is unlikely to show you anything very interesting even if you do use a profiling technique that works for native code. The WaitHandle is going to wait until something signals it and that signal is going to come from another thread. It usually requires some understanding of the code that is manipulating the WaitHandle (PersistenceChannelSender.SendLoop() in this case) to determine what condition would let it proceed.
2. Each sample in this view only means that time passed at the specified callstack, not necessarily that CPU cycles were used by the thread during that time. The native code implementation of a WaitHandle calls into the windows kernel to block on an OS synchronization primitive and then the scheduler reassigns the CPU core to some other thread so it probably wasn't using any CPU at all.

Hope that helps

**Comment by brianrob** [comment] 2022-06-13 23:06
Bulk closing old issues.  Please re-open if needed.

**Closed by brianrob** 2022-06-13 23:06 UTC
